import { IAudioSrc } from '../../../types/interfaces';

export const tasks: IAudioSrc = {
  km: require('./km.mp3'),
  a: require('./a.mp3'),
  u: require('./u.mp3'),
  s: require('./s.mp3'),
  r: require('./r.mp3'),
  t: require('./t.mp3'),
  o: require('./o.mp3'),
  p: require('./p.mp3'),
  n: require('./n.mp3'),
  h: require('./h.mp3'),
  z: require('./z.mp3'),
  i: require('./i.mp3'),
  e: require('./e.mp3'),
  w: require('./w.mp3'),
  d: require('./d.mp3'),
  g: require('./g.mp3'),
  l: require('./l.mp3'),
  f: require('./f.mp3'),
  v: require('./v.mp3'),
  b: require('./b.mp3'),
  q: require('./q.mp3'),
  c: require('./c.mp3'),
  che: require('./che.mp3'),
  y: require('./y.mp3'),
  sh: require('./sh.mp3'),
  ia: require('./ia.mp3'),
  x: require('./x.mp3'),
  j: require('./j.mp3'),
  iu: require('./iu.mp3'),
  ae: require('./ae.mp3'),
};
